version: '3.8'

services:
  mysql:
    image: mysql:8.4.6
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password-root
      MYSQL_DATABASE: test_plus
      MYSQL_USER: mario_plus
      MYSQL_PASSWORD: password-mario
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_net

volumes:
  mysql_data:

networks:
  app_net:
    driver: bridge
